import type { Flow } from "../types";

/** A fictional engagement: supplier invoices stall in approval at a mid-size distributor. Every figure is the client's, never the engine's. */
export const invoiceApprovals: Flow = {
  slug: "invoice-approvals",
  engagement: {
    client: "Rawdah Distribution Co.",
    scope: "Accounts payable: supplier invoice approvals",
    interviewee: "Finance Operations Manager",
    profile: "Enterprise",
    stage: "MVP",
  },
  stages: [
    { id: "setup", label: "Setup" },
    { id: "context", label: "Context" },
    { id: "pain", label: "Pain capture" },
    { id: "diagnosis", label: "Diagnosis" },
    { id: "hypotheses", label: "Hypotheses" },
    { id: "pillars", label: "Pillar sweep" },
    { id: "prioritise", label: "Prioritise" },
    { id: "solution", label: "Solution" },
    { id: "gates", label: "Gates" },
    { id: "outputs", label: "Outputs" },
  ],
  checklist: [
    { id: "felt-pain", label: "Pain in the client's own words", group: "Pain", weight: 6, rule: "D1" },
    { id: "affected", label: "Who carries the cost", group: "Pain", weight: 6 },
    { id: "volume", label: "Frequency and volume", group: "Pain", weight: 7 },
    { id: "process", label: "As-is process walked through", group: "Pain", weight: 7 },
    { id: "evidence", label: "Evidence attached", group: "Pain", weight: 6 },
    { id: "shadow", label: "Shadow systems registered", group: "Pain", weight: 4 },
    { id: "quantified", label: "Impact quantified", group: "Quantification", weight: 14, rule: "D3" },
    { id: "basis", label: "Basis and confidence stated", group: "Quantification", weight: 6, rule: "D3" },
    { id: "ladder", label: "Why-ladder recorded", group: "Root cause", weight: 8 },
    { id: "solvable", label: "Solvable layer marked", group: "Root cause", weight: 10, rule: "D4" },
    { id: "hypothesis", label: "Hypothesis tested against a fact", group: "Solution and risk", weight: 7, rule: "D5" },
    { id: "sponsor", label: "Sponsor identified", group: "Solution and risk", weight: 6 },
    { id: "obstacles", label: "Obstacles named", group: "Solution and risk", weight: 6, rule: "D2" },
    { id: "pillars", label: "Every pillar has a verdict", group: "Solution and risk", weight: 7, rule: "D6" },
  ],
  start: "open",
  steps: {
    open: {
      id: "open",
      ask: "Thanks for making the time. Before we talk about systems at all: what is the one part of your week that, if it disappeared, would make the biggest difference to you and your team?",
      method: { rule: "D1", text: "Open on felt pain, never on a list of gaps." },
      input: { kind: "text", answer: "Honestly? Chasing invoice approvals. Every month-end we're begging managers to approve invoices that have sat for a week or more, and suppliers are phoning us asking where their money is." },
      effects: [
        { type: "stage", stage: "pain" },
        { type: "note", tag: "quote", text: "\"Every month-end we're begging managers to approve invoices.\"" },
        { type: "note", tag: "symptom", text: "Supplier invoices sit unapproved for a week or more." },
        { type: "pain", title: "Supplier invoices stall in approval", status: "symptom" },
        { type: "check", id: "felt-pain" },
      ],
      next: "who",
    },
    who: {
      id: "who",
      ask: "Who feels that most when it happens?",
      method: { text: "Find who carries the cost. The loudest voice is not always the biggest cost." },
      input: {
        kind: "choice",
        suggested: 0,
        options: [
          { label: "My team in Finance", detail: "Time lost chasing", next: "finance-load", effects: [{ type: "note", tag: "symptom", text: "AP team spends month-end chasing approvals instead of closing." }, { type: "check", id: "affected" }] },
          { label: "Our suppliers", detail: "Late payment, calls", next: "supplier-impact", effects: [{ type: "note", tag: "symptom", text: "Suppliers chase payment status by phone." }, { type: "check", id: "affected" }] },
          { label: "Leadership, at month-end", detail: "Late close", next: "close-impact", effects: [{ type: "note", tag: "symptom", text: "Month-end close slips while approvals are outstanding." }, { type: "check", id: "affected" }] },
        ],
      },
      effects: [],
    },
    "finance-load": {
      id: "finance-load",
      ask: "How many people are involved, and how much of their week goes on chasing?",
      method: { text: "Volume before solutions. A number now saves a debate later." },
      input: { kind: "text", answer: "There are six of us in AP. At month-end it's most of two people's time; the rest of the month maybe a day a week each, just following up." },
      effects: [{ type: "note", tag: "fact", text: "AP team of 6; about 2 FTE at month-end and 1 day/week each otherwise go on follow-up." }, { type: "check", id: "volume" }],
      next: "process",
    },
    "supplier-impact": {
      id: "supplier-impact",
      ask: "How often do suppliers chase, and has it cost you anything yet?",
      method: { text: "Volume before solutions. A number now saves a debate later." },
      input: { kind: "text", answer: "Forty to fifty calls a month. Two suppliers put us on stop last quarter, and we miss early-payment discounts all the time." },
      effects: [{ type: "note", tag: "fact", text: "40 to 50 supplier chase calls a month; 2 suppliers put the account on stop last quarter." }, { type: "note", tag: "symptom", text: "Early-payment discounts routinely missed." }, { type: "check", id: "volume" }],
      next: "process",
    },
    "close-impact": {
      id: "close-impact",
      ask: "How late does the close run, and what does that delay?",
      method: { text: "Volume before solutions. A number now saves a debate later." },
      input: { kind: "text", answer: "Two to three days most months. The CFO pack goes out late, and we accrue blind for anything that isn't approved yet." },
      effects: [{ type: "note", tag: "fact", text: "Close runs 2 to 3 days late; unapproved invoices accrued without detail." }, { type: "check", id: "volume" }],
      next: "process",
    },
    process: {
      id: "process",
      ask: "Walk me through one invoice, from the moment it arrives to the moment it's paid. Don't skip the boring bits.",
      method: { text: "Map the as-is process. The pain usually hides in the hand-offs." },
      input: { kind: "text", answer: "It lands in the AP inbox as a PDF. We key it into Oracle, then email the budget holder to approve. They reply \"approved\", we update our tracker spreadsheet, and it goes into the Thursday payment run. If they don't reply, we chase." },
      effects: [
        { type: "note", tag: "fact", text: "PDF to AP inbox, keyed into Oracle, approval by email, tracker spreadsheet, Thursday payment run." },
        { type: "note", tag: "symptom", text: "Approval happens by email, outside the ERP. Every invoice is re-keyed by hand." },
        { type: "hypothesis", id: "h-capture", name: "Invoice capture: PDF to Oracle", shape: "Agentic applet", status: "open", reason: "Every invoice is re-keyed by hand." },
        { type: "check", id: "process" },
      ],
      next: "screenshot",
    },
    screenshot: {
      id: "screenshot",
      ask: "That tracker sounds important. Could you share a screenshot of it? Real data is fine; it's stored as confidential evidence for this engagement only.",
      method: { text: "Evidence over anecdote. A screenshot shows volumes, ageing and workarounds nobody mentions." },
      input: { kind: "upload", file: "AP approvals tracker.xlsx", caption: "Screenshot of the AP approvals tracker" },
      effects: [
        { type: "note", tag: "evidence", text: "Tracker shows 214 invoices awaiting approval; 61 are older than 10 days." },
        { type: "note", tag: "fact", text: "Shadow system: AP approvals tracker (Excel), kept by AP because Oracle approvals are not switched on." },
        { type: "pain", status: "candidate" },
        { type: "check", id: "evidence" },
        { type: "check", id: "shadow" },
      ],
      next: "quantify",
    },
    quantify: {
      id: "quantify",
      ask: "Let's put a number on it, using your figures, not ours. I've pre-filled what you've told me; correct anything that's off.",
      method: { rule: "D3", text: "Quantify it or it isn't a pain point. Every figure has a source and a confidence." },
      input: {
        kind: "roi",
        currency: "SAR",
        confidence: "Medium",
        basis: "Volumes from the AP lead and the tracker; staff cost from the HR band; discount terms from the top 20 supplier contracts (to verify).",
        fields: [
          { id: "invoices", label: "Invoices per month", value: 1850, unit: "invoices", source: "Tracker" },
          { id: "minutes", label: "Handling time per invoice", value: 9, unit: "min", source: "AP lead" },
          { id: "rate", label: "Loaded staff cost", value: 95, unit: "SAR/h", source: "HR band" },
          { id: "eligible", label: "Discount-eligible spend / month", value: 600000, unit: "SAR", source: "Contracts" },
          { id: "discount", label: "Early-payment discount", value: 2, unit: "%", source: "Contracts" },
          { id: "missed", label: "Discounts missed", value: 60, unit: "%", source: "AP lead" },
        ],
        compute: (v) => {
          const hours = (v.invoices * 12 * v.minutes) / 60;
          return [
            { label: "Staff time", working: `${fmt(v.invoices)} × 12 × ${v.minutes} min ÷ 60 = ${fmt(hours)} h × ${v.rate}`, value: hours * v.rate },
            { label: "Missed discounts", working: `${fmt(v.eligible)} × 12 × ${v.discount}% × ${v.missed}%`, value: v.eligible * 12 * (v.discount / 100) * (v.missed / 100) },
          ];
        },
      },
      effects: [
        { type: "stage", stage: "diagnosis" },
        { type: "pain", status: "confirmed" },
        { type: "check", id: "quantified" },
        { type: "check", id: "basis" },
      ],
      next: "why",
    },
    why: {
      id: "why",
      ask: "Now the why. I'll keep asking until we reach something we can build a fix for, then mark that layer.",
      method: { rule: "D4", text: "Find the root cause at the buildable layer: deep enough to fix, and no deeper." },
      input: {
        kind: "ladder",
        solvable: 2,
        rungs: [
          { why: "Why do invoices wait so long?", because: "Budget holders don't know an invoice is waiting for them." },
          { why: "Why don't they know?", because: "Requests arrive as ordinary emails and get buried." },
          { why: "Why is approval done by email?", because: "Oracle's approval workflow was never configured, so the tracker grew to fill the gap." },
          { why: "Why was it never configured?", because: "The ERP rollout ran out of budget, and nobody has owned finance systems since.", obstacle: true },
        ],
      },
      effects: [
        { type: "stage", stage: "hypotheses" },
        { type: "check", id: "ladder" },
        { type: "check", id: "solvable" },
        { type: "hypothesis", id: "h-erp", name: "Switch on Oracle approval workflow", shape: "ERP configuration", status: "open", reason: "Targets the solvable layer directly." },
        { type: "hypothesis", id: "h-nudge", name: "Approval nudges in Teams and email", shape: "Agentic applet", status: "open", reason: "Works around the ERP if configuring it is blocked." },
      ],
      next: "licence",
    },
    licence: {
      id: "licence",
      ask: "A quick check that changes the shape of the answer: is Oracle's approval module included in your current licence?",
      method: { rule: "D5", text: "Test hypotheses during discovery. One answer can kill a solution shape." },
      input: {
        kind: "choice",
        suggested: 0,
        options: [
          { label: "Yes, licensed but unused", next: "sponsor", effects: [
            { type: "note", tag: "fact", text: "Oracle approval module is licensed but unused." },
            { type: "hypothesis", id: "h-erp", status: "strengthened", reason: "Already licensed: configuration, not new software." },
            { type: "hypothesis", id: "h-nudge", status: "killed", reason: "Not needed if the ERP sends its own notifications." },
            { type: "check", id: "hypothesis" },
          ] },
          { label: "No, we'd have to buy it", next: "sponsor", effects: [
            { type: "note", tag: "fact", text: "Approval module not in the current licence." },
            { type: "hypothesis", id: "h-erp", status: "open", reason: "Licence cost to be priced against the pain." },
            { type: "hypothesis", id: "h-nudge", status: "strengthened", reason: "Works with today's licence." },
            { type: "check", id: "hypothesis" },
          ] },
          { label: "Not sure", next: "sponsor", effects: [
            { type: "note", tag: "fact", text: "Licence status unknown. Action: IT to confirm." },
            { type: "check", id: "hypothesis" },
          ] },
        ],
      },
      effects: [],
    },
    sponsor: {
      id: "sponsor",
      ask: "If we fixed this, who would need to say yes, and who might quietly say no?",
      method: { rule: "D2", text: "Name the obstacles early, as their own stream. Politics stops more projects than technology does." },
      input: { kind: "text", answer: "The CFO would back it tomorrow. The Head of IT is the one to convince; they're stretched, and still sore about the ERP project." },
      effects: [
        { type: "note", tag: "fact", text: "Sponsor: CFO, a champion." },
        { type: "obstacle", text: "No owner for finance systems since the ERP rollout", who: "Head of IT", stance: "resistant", influence: "H" },
        { type: "obstacle", text: "IT capacity is stretched", who: "Head of IT", stance: "neutral", influence: "M" },
        { type: "check", id: "sponsor" },
        { type: "check", id: "obstacles" },
      ],
      next: "pillars",
    },
    pillars: {
      id: "pillars",
      ask: "Before we close, a sweep across every pillar. Each one gets a verdict and a reason; none is left blank.",
      method: { rule: "D6", text: "Visit every pillar; you don't have to work every pillar." },
      input: {
        kind: "pillars",
        pillars: [
          { id: "P1", name: "Strategy and alignment", verdict: "core", reason: "Cash and close KPIs" },
          { id: "P2", name: "Governance", verdict: "core", reason: "Approval rights, RACI" },
          { id: "P3", name: "Risk management", verdict: "deferred", reason: "Vendor risk, next phase" },
          { id: "P4", name: "Customer experience", verdict: "na", reason: "No end-customer journey" },
          { id: "P5", name: "Process and operations", verdict: "core", reason: "The invoice journey" },
          { id: "P6", name: "Data management", verdict: "core", reason: "Supplier master quality" },
          { id: "P7", name: "Architecture and integration", verdict: "core", reason: "Oracle, email, Teams" },
          { id: "P8", name: "Security and privacy", verdict: "core", reason: "Segregation of duties" },
          { id: "P9", name: "Technology and platforms", verdict: "core", reason: "Unused Oracle modules" },
          { id: "P10", name: "People and change", verdict: "core", reason: "Budget holder adoption" },
          { id: "P11", name: "Compliance", verdict: "deferred", reason: "ZATCA e-invoicing check" },
          { id: "P12", name: "Financial and value", verdict: "core", reason: "Quantified above" },
          { id: "P13", name: "AI and innovation", verdict: "deferred", reason: "Invoice capture, phase 2" },
          { id: "P14", name: "Service management", verdict: "deferred", reason: "Post go-live support" },
          { id: "P15", name: "Performance measurement", verdict: "core", reason: "Baseline: approval age" },
        ],
      },
      effects: [{ type: "stage", stage: "pillars" }, { type: "check", id: "pillars" }],
      next: "gates",
    },
    gates: {
      id: "gates",
      ask: "Here's where we stand against the MVP gates. The engine won't produce a specification while a hard gate is open: satisfy it, or defer it with a reason.",
      method: { rule: "D7", text: "Gates can't be skipped. Corners cut are chosen and recorded, never forgotten." },
      input: {
        kind: "gates",
        stage: "MVP",
        gates: [
          { id: "G1", label: "Every pillar has a verdict", hard: true, satisfiedBy: "pillars", deferReason: "", deferTo: "" },
          { id: "G2", label: "Each in-scope pain point quantified", hard: true, satisfiedBy: "quantified", deferReason: "", deferTo: "" },
          { id: "G3", label: "Solvable root-cause layer identified", hard: true, satisfiedBy: "solvable", deferReason: "", deferTo: "" },
          { id: "G4", label: "Sponsor identified and engaged", hard: true, satisfiedBy: "sponsor", deferReason: "", deferTo: "" },
          { id: "G5", label: "Top obstacles have a mitigation", hard: true, deferReason: "Mitigation agreed at the CFO and Head of IT session next week.", deferTo: "MVP week 1" },
          { id: "G6", label: "Authoritative owner per data component", hard: true, deferReason: "Supplier master owner to be named by the CFO.", deferTo: "MVP week 2" },
          { id: "G12", label: "Success metrics with a baseline", hard: true, deferReason: "Baseline approval age to be pulled from the tracker history.", deferTo: "MVP week 1" },
          { id: "G11", label: "Hosting and data residency decided", hard: false, deferReason: "Oracle Cloud region already in KSA.", deferTo: "Production" },
        ],
      },
      effects: [{ type: "stage", stage: "gates" }],
      next: "end",
    },
    end: {
      id: "end",
      ask: "Discovery summary drafted. Every line traces back to an answer, a figure or a piece of evidence above.",
      method: { text: "Output is generated from structured findings, not free text." },
      input: { kind: "end" },
      effects: [],
    },
  },
};

function fmt(n: number) { return Math.round(n).toLocaleString("en-US"); }
